# Generated by Django 5.1.4 on 2024-12-18 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='meals',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='daily_calorie_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealplans', to=settings.AUTH_USER_MODEL),
        ),
    ]
