# Generated by Django 5.1.4 on 2024-12-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_remove_recipe_calories_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
